"""empty message

Revision ID: 5c8b68437af4
Revises: 
Create Date: 2020-12-24 09:31:02.663024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8b68437af4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carName', sa.String(length=80), nullable=True),
    sa.Column('carAge', sa.String(length=4), nullable=True),
    sa.Column('carDetail', sa.String(length=100), nullable=True),
    sa.Column('carImage', sa.String(length=100), nullable=True),
    sa.Column('isRent', sa.Boolean(), nullable=True),
    sa.Column('kiralanmaSayisi', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('kiralikAracSayisi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rentcars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rentDate', sa.DateTime(), nullable=True),
    sa.Column('carId', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carId'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rentcars')
    op.drop_table('users')
    op.drop_table('cars')
    # ### end Alembic commands ###
